### ISSUE TITLE
Allow user to specify the config object for each use of the form directive

### ISSUE THREAD

**Issue by jbalbes** [Expium/jira-item-form#8]
This would probably take the form of two potential attributes on the directive. One takes an object from the outer scope (for use inside an angular app) and the other will look for a global object (the way that it works now). In either case, this will remove the hard coded name for the config object

**Comment by kylecordes** [comment]
Once the mechanism is in place, it is probably best to always use it - rather than sometimes looking around for a global config.

**Comment by jbalbes** [comment]
This was released with version 0.0.12
